apiVersion: ops.gouster.io/v1alpha1
kind: EnvironmentSchedule
metadata:
  labels:
    app.kubernetes.io/name: cost-optimizer
    app.kubernetes.io/managed-by: kustomize
  name: environmentschedule-sample
spec:
  shutdownHour: 20
  startupHour: 7
  timeZone: "Europe/Madrid"